### ISSUE TITLE
Task: Double check babies whose reported lang_group did not match lang_group according to exposure

### ISSUE THREAD

**Issue by kristabh** [kristabh/gaze-following-analysis#15]

**Comment by Joscelinrocha** [comment]
working on it

**Comment by Joscelinrocha** [comment]
There were 63 codes whose Lang_group reported did not match the lang_group later calculated:
- babylab-brookes = 20-> there are 2 codes with missing info for Language and 3 codes with a shifted column. Need to follow up with them. 
- cdc-ceu = 2
- elp-georgetown = 11
- irl-concordia = 2
- lll-liv = 4
- nusinfantlanguagecentre = 2
- upf_barcelona = 8 <- need to follow up. One subject shows as 5% L1 and 44% L2. They reported it as bilingual so something seems wrong.
- babylab-princeton = 5 <- one subject has .7 in L1. and 30 in L2. Maybe it was meant to be 70%?
- babylab-westernsydney = 5 <- typo in English (need to be fixed)
- bll-umanitoba = 3
- infantlanglab-utk= 1
Here is a quick table I was using to keep track of them. 
[Lang_group_not_matching.xlsx]

There was a common error of people labeling bilinguals using a 20% min or monolinguals to those who did not meet the 20/25% L2, not the 90%. 
I also noticed that some labs were reporting their codes as other but we labeled them as monolinguals because they were 90 or more L1. But I think they were labeled "other" because their L1 was not the "community language".  Just looking really quickly over the data around 7 codes we label as monolinguals had primary languages different from the community (ignoring the Catalan/Spanish from Barcelona or French/English from Canada). Should we drop those kids? Do we have information on what the community languages are at each site?

**Comment by Joscelinrocha** [comment]
[Lang_group_not_matching.xlsx](https://github.com/kristabh/gaze-following-analysis/files/3199255/Lang_group_not_matching.xlsx)

**Comment by kristabh** [comment]
Fixed Princeton issue - was a percentage sign in Excel that was causing problems.
