### ISSUE TITLE
Task: Check preterm in variable_validation

### ISSUE THREAD

**Issue by kristabh** [kristabh/gaze-following-analysis#17]
Consider revisiting preterm status. Currently code is commented out.

**Comment by melsod** [comment]
I'll take a look.

**Comment by melsod** [comment]
Haha, lots of issues here! To check/confirm (might be able to just look at the MB preterm spreadsheet?):

Brookes - just confirm days_preterm < 37 or < 40
cdc-ceu mb37 typo? baby is listed as not preterm but days = 28
utk - used <40 as their standard for both Y/N and days_preterm?
georgetown - something really wonky - days_preterm = 266, 3.5 etc.
nus - check - 4/13 listed as preterm, high N of days PT.
concordia - days_preterm < 40?
zurich - days_preterm < 40?

**Comment by melsod** [comment]
also, koku-hamburg has one participant (MB_19_gf) listed with days_preterm but not marked as preterm.

**Comment by Joscelinrocha** [comment]
answers for above:
Brookes - used < 37 
cdc-ceu mb37 typo? baby is listed as not preterm but days = 28--> they listed it that way because parents said that the child was not premature but later declared that the baby was born after 36weeks. Lab decided to mark child as term. 
utk - waiting for answers but went ahead and changed N/Y for term and preterm
georgetown - was using 40 weeks as a reference instead of 37 and changes were made. There were a couple of children whose parents reported the number of weeks they were born at instead of the weeks premature which caused weird numbers.
nus - lab used 37 weeks as criteria for preterm
concordia - days_preterm < 37
zurich - days_preterm < 40

**Comment by kristabh** [comment]
Great!  Updated the /metadata/preterm_fix document.  The only lab we are missing data on preterm criteria is babylab-westernsydney

**Comment by Joscelinrocha** [comment]
babylab-westernsydney - preterm is <37 weeks gestation

**Comment by kristabh** [comment]
Great!  Is there anything else, or can this issue be closed?

**Comment by Joscelinrocha** [comment]
I think that was it. It can be closed.
