### ISSUE TITLE
d_first_meta: why remove subgroups with fewer than 10 babies?

### ISSUE THREAD

**Issue by AlexisBlack2g** [kristabh/gaze-following-analysis#34]
I don't think this particular restriction is in the pre-reg, right?  Is it from the MB1 or MB1B analyses?
Doing this does remove one problem in the data - we currently have data from not mono and not bilingual babies as well as 3-6 and 9-12 mo babies.  I believe all of these cases, however, have fewer than 10 subs, so are removed from the meta-analysis.

**Comment by kristabh** [comment]
Yeah, this is from MB1/B.  The rationale there was that if there are groups with fewer than 10, then the estimate of the meta-analytic effect size is unstable.  I think we could go either way.  You're right that we didn't pre-reg anything about this, probably because we didn't expect any labs would end up with fewer than 10 since the target was a min of 16.

**Comment by kristabh** [comment]
But age and language-based exclusions should be taken care of in the paper/exclusions script. This gets called in the 03_exclusions script, but only when it gets knitted.  It's kind of confusing, but it was set up that way in the mb1 script which I based this off of.  So make sure to run the paper/exclusions script prior to running the 03_exclusions script to exclude babies properly.

**Comment by AlexisBlack2g** [comment]
Ah, thanks - I thought I'd seen the exclusions filtering these out!  I ran the chunks in 03_exclusions, but maybe that didn't call in the child exclusions script (or I managed to write-out the wrong file, or something- will check on it)
